translate = {
  "apple": "olma",
  "make an occusation": "ayblamoq",
  "make a demand": "talab qilmoq",
  "make an announcement": "e'lon qilmoq",
  "make an application": "ariza bermoq",
  "make a list": "roʻyxatga olmoq",
  "make an argument": "kelishmoq",
  "make an attempt": "urunmoq",
  "make a choice": "tanlamoq",
  "make a difference": "farqlamoq",
  "make a remark": "izohlamoq",
  "make a speech": "nutq soʻzlamoq",
  "make a suggestion": "taklif qilmoq",
  "make an affort": "harakat qilmoq",
  "make progress": "ulgurmoq, ildamlash",
  "make a will": "vasiyat qilmoq",
  "make friends": "doʻstlar orttiqmoq",
  "make a comment": "sharxlamoq",
  "make an excuse": "uzr sòramoq",
  "make a money": "pul ishlab topmoq",
  "make a plan": "reja tuzmoq",
  "make a point": "maqsad qilmoq",
  "make a promise": "va'da bermoq",
  "make a mess": "tartibsizlik qilmoq",
  "make a less": "yoʻqotish",
  "make a proposal": "yoʻqotish",
  "make a sound": "ovoz chiqarmoq",
  "call around": "tashrif buyurmoq",
  "call back": "qaytib qo’ng’iroq qilmoq",
  "call on": "yordam so’ramoq",
  "carry off": "g’alaba qilmoq, kasallikdan o’lmoq",
  "catch on": "mashxurlik qozonmoq",
  "charge with": "jinoyatda ayblamoq",
  "cheer up": "undamoq, ruhlantirmoq",
  "chill out": "dam olmoq",
  "clear away": "manzilni tark etish",
  "close up": "to’liq yopish, birlashtirish, yaqinlashish",
  "come down with": "kasal bo’lmoq",
  "cry off": "kelishuvni bekor qilish",
  "take after": "o’xshamoq",
  "tuck away": "xavfsiz joyga qo’yish",
  "turn up": "ovozini ko’tarish, kelish, paydo bo’lish",
  "own up to": "tan olish, bo’yniga olish",
  "opt for": "tanlamoq",
  "reckon on": "eng kamida deb hisoblash",
  "run on": "hisobiga yurmoq",
  "rope in": "kimnidir yordam berishga jalb qilish",
  "set aside": "sudda davo/hukmni bekor qilish",
  "show off": "maqtanib ko’z-ko’z qilmoq",
  "wear out": "tamom bo’lgunicha ishlatish",
  "wear down": "kuchsizlantirish",
  "desire": "istak, hoxish",
  "glory": "sharaf, go'zallik",
  "pumpkin": "qovoq",
  "experience": "tajriba",
  "reconcile": "yarash(tir)moq",
  "astonishing": "hayratda qoldiradigan",
  "child": "bola",
  "sophisticate": "nozik, nafis",
  "regret": "pushaymonlik",
  "rebel": "isyon, isyonchi",
  "tranquil": "bosilgan, vazmin",
  "sunrise": "quyoshning chiqishi",
  "sunset": "quyosh botishi",
  "fabulous": "aqil bovar qilmas",
  "meadow": "o'tloq, yaylov",
  "reflection": "aks, tasir",
  "passion": "ehtiros",
  "umbrella": "soyabon",
  "lollipop": "xo'razqand",
  "banana": "banan",
  "animal": "jonivor",
  "perfection": "mukammalik",
  "mother": "ona",
  "important": "muhim",
  "gorgeous": "juda yaxshi ajoib",
  "sweetheart": "shirin qalb",
  "butterfly": "kapalak",
  "godsend": "g'oyibdan kelgan omad, baxt",
  "unique": "yakkayu yagona",
  "summer": "yoz"
}
