translate = {
  "apple": "olma",
  "make an occusation": "ayblamoq",
  "make a demand": "talab qilmoq",
  "make an announcement": "e'lon qilmoq",
  "make an application": "ariza bermoq",
  "make a list": "roʻyxatga olmoq",
  "make an argument": "kelishmoq",
  "make an attempt": "urunmoq",
  "make a choice": "tanlamoq",
  "make a difference": "farqlamoq",
  "make a remark": "izohlamoq",
  "make a speech": "nutq soʻzlamoq",
  "make a suggestion": "taklif qilmoq",
  "make an affort": "harakat qilmoq",
  "make progress": "ulgurmoq, ildamlash",
  "make a will": "vasiyat qilmoq",
  "make friends": "doʻstlar orttiqmoq",
  "make a comment": "sharxlamoq",
  "make an excuse": "uzr sòramoq",
  "make a money": "pul ishlab topmoq",
  "make a plan": "reja tuzmoq",
  "make a point": "maqsad qilmoq",
  "make a promise": "va'da bermoq",
  "make a mess": "tartibsizlik qilmoq",
  "make a less": "yoʻqotish",
  "make a proposal": "yoʻqotish",
  "make a sound": "ovoz chiqarmoq"
}
